/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as HostRouteImport } from './routes/host'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBookingsRouteImport } from './routes/app/bookings'
import { Route as AppLiveRouteImport } from './routes/app/live'
import { Route as AppYouRouteImport } from './routes/app/you'
import { Route as HostIndexRouteImport } from './routes/host/index'
import { Route as HostBookingsRouteImport } from './routes/host/bookings'
import { Route as HostMoreRouteImport } from './routes/host/more'
import { Route as HostPerksRouteImport } from './routes/host/perks'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppRestaurantIdRouteImport } from './routes/app/restaurant.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppYouRoute = AppYouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => AppRoute,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRoute,
} as any)
const HostBookingsRoute = HostBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => HostRoute,
} as any)
const HostMoreRoute = HostMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => HostRoute,
} as any)
const HostPerksRoute = HostPerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => HostRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestaurantIdRoute = AppRestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/live': typeof AppLiveRoute
  '/app/you': typeof AppYouRoute
  '/host/bookings': typeof HostBookingsRoute
  '/host/more': typeof HostMoreRoute
  '/host/perks': typeof HostPerksRoute
  '/app/': typeof AppIndexRoute
  '/host/': typeof HostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/restaurant/$id': typeof AppRestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/live': typeof AppLiveRoute
  '/app/you': typeof AppYouRoute
  '/host/bookings': typeof HostBookingsRoute
  '/host/more': typeof HostMoreRoute
  '/host/perks': typeof HostPerksRoute
  '/app': typeof AppIndexRoute
  '/host': typeof HostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/restaurant/$id': typeof AppRestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/live': typeof AppLiveRoute
  '/app/you': typeof AppYouRoute
  '/host/bookings': typeof HostBookingsRoute
  '/host/more': typeof HostMoreRoute
  '/host/perks': typeof HostPerksRoute
  '/app/': typeof AppIndexRoute
  '/host/': typeof HostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/restaurant/$id': typeof AppRestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/host'
    | '/login'
    | '/signup'
    | '/app/bookings'
    | '/app/live'
    | '/app/you'
    | '/host/bookings'
    | '/host/more'
    | '/host/perks'
    | '/app/'
    | '/host/'
    | '/api/auth/$'
    | '/app/restaurant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/bookings'
    | '/app/live'
    | '/app/you'
    | '/host/bookings'
    | '/host/more'
    | '/host/perks'
    | '/app'
    | '/host'
    | '/api/auth/$'
    | '/app/restaurant/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/host'
    | '/login'
    | '/signup'
    | '/app/bookings'
    | '/app/live'
    | '/app/you'
    | '/host/bookings'
    | '/host/more'
    | '/host/perks'
    | '/app/'
    | '/host/'
    | '/api/auth/$'
    | '/app/restaurant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HostRoute: typeof HostRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live': {
      id: '/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/you': {
      id: '/app/you'
      path: '/you'
      fullPath: '/app/you'
      preLoaderRoute: typeof AppYouRouteImport
      parentRoute: typeof AppRoute
    }
    '/host/': {
      id: '/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/bookings': {
      id: '/host/bookings'
      path: '/bookings'
      fullPath: '/host/bookings'
      preLoaderRoute: typeof HostBookingsRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/more': {
      id: '/host/more'
      path: '/more'
      fullPath: '/host/more'
      preLoaderRoute: typeof HostMoreRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/perks': {
      id: '/host/perks'
      path: '/perks'
      fullPath: '/host/perks'
      preLoaderRoute: typeof HostPerksRouteImport
      parentRoute: typeof HostRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/restaurant/$id': {
      id: '/app/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/app/restaurant/$id'
      preLoaderRoute: typeof AppRestaurantIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBookingsRoute: typeof AppBookingsRoute
  AppLiveRoute: typeof AppLiveRoute
  AppYouRoute: typeof AppYouRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRestaurantIdRoute: typeof AppRestaurantIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingsRoute: AppBookingsRoute,
  AppLiveRoute: AppLiveRoute,
  AppYouRoute: AppYouRoute,
  AppIndexRoute: AppIndexRoute,
  AppRestaurantIdRoute: AppRestaurantIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface HostRouteChildren {
  HostBookingsRoute: typeof HostBookingsRoute
  HostMoreRoute: typeof HostMoreRoute
  HostPerksRoute: typeof HostPerksRoute
  HostIndexRoute: typeof HostIndexRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostBookingsRoute: HostBookingsRoute,
  HostMoreRoute: HostMoreRoute,
  HostPerksRoute: HostPerksRoute,
  HostIndexRoute: HostIndexRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HostRoute: HostRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
